GET_AWAY_DISTANCE: 30000
MACHINEGUN_DAMAGE: 20
MACHINEGUN_GAUGE: 400
MACHINEGUN_RANGE: 1000
MACHINEGUN_SHOTS: 3
MACHINEGUN_SWORD_GAUGE_DAMAGE: 300 
MACHINEGUN_WIN: 10
NEARBY: 1000
RIFLE_ATTACK_TIME_LIMIT: 20000
RIFLE_DAMAGE: 100
RIFLE_GAUGE: 5000
RIFLE_MAX_DISTANCE: 40000
RIFLE_MIN_DISTANCE: 2000
RIFLE_SWORD_GAUGE_DAMAGE: 600 
RIFLE_WIN: 11
RIFLE_LANDED_BONUS: 1
RIFLE_ENERGY: 30000
RIFLE_ENERGY_NEEDED: 20000
SWORD_ATTACK_TIME_LIMIT: 4000
SWORD_BOUNCE: 200
SWORD_DAMAGE: 200
SWORD_DAMAGE_BONUS_FACTOR: 15
SWORD_DISTANCE: 10
SWORD_GAUGE_VELOCITY_BONUS: 20
SWORD_VELOCITY: 8
SWORD_WIN: 12
SWORD_ENERGY: 50000
SWORD_ENERGY_NEEDED: 30000
VELOCITY_LIMIT: 11
LANDING_RANGE: 20000
LANDING_VELOCITY: 3
LANDING_DISTANCE: 10
SIGHT_TOLERANCE: 10000
SIGHT_LANDED_BONUS: 40000
SIGHT_SENSOR_ARRAY_BONUS: 100000
SIGHT_MINIMUM: 10000
BOOST_GAUGE: 50000
BOOST_VELOCITY: 9
SUPPORT_GAUGE: 14000
ENERGY_STANDARD_BONUS: 1
ENERGY_HIGH_VELOCITY_MALUS: 1
ENERGY_MAX_VELOCITY_MALUS: 2
ENERGY_SWORD_VELOCITY_MALUS: 4
ENERGY_BOOST_MALUS: 5
ENERGY_AVAILABLE_FOR_HIGH_SPEED: 1000
ENERGY_GAUGE: 1
INERTIA_RIFLE_TOO_CLOSE: 200
INERTIA_SWORD_SLASH: 700
INERTIA_SWORD_DODGE: 500
INERTIA_SWORD_NULLIFIED: 400
INERTIA_RIFLE_SHOT: 400
INERTIA_SECOND_SIGHT: 300
