MACHINEGUN_GAUGE: 800
MACHINEGUN_RANGE: 1500
MACHINEGUN_DAMAGE: 100
RIFLE_DAMAGE: 300
RIFLE_GAUGE: 15000
RIFLE_MAX_DISTANCE: 15000
SWORD_DAMAGE: 400
SWORD_DAMAGE_BONUS_FACTOR: 25
SIGHT_TOLERANCE: 1000
SIGHT_MINIMUM: 1000
SUPPORT_GAUGE: 4000
ENERGY_GAUGE: 50
DICE_RESULTS: 
    drift direction: 0
NO_HITTING_LUCK: 1
