MACHINEGUN_GAUGE: 800
MACHINEGUN_RANGE: 1500
RIFLE_DAMAGE: 300
RIFLE_GAUGE: 15000
RIFLE_MAX_DISTANCE: 15000
SWORD_DAMAGE: 400
SIGHT_TOLERANCE: 1000
SIGHT_MINIMUM: 1000
SUPPORT_GAUGE: 4000
ENERGY_GAUGE: 50
